import Link from 'next/link';
import './globals.css';
import { Control } from './control';

export const metadata = {
  title: 'WEB tutorial',
  description: 'Generated by egoing',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // API URL과 캐싱 설정을 통해 topics 데이터 가져오기
  const resp = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics`, {
    cache: 'no-store', // 매번 최신 데이터를 가져오도록 캐싱 비활성화
  });
  const topics = await resp.json();

  return (
    <html lang="en">
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic: { id: string; title: string }) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}