import Link from 'next/link';
import './globals.css';
import { Control } from './control';
import { TopicsProvider } from './topicsProvider';

export const metadata = {
  title: 'WEB tutorial',
  description: 'Generated by egoing',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}posts/list`,
    { cache: 'no-store' }
  );
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <TopicsProvider initialTopics={topics.data}>
          {children}
          <Control />
          <ol>
            {topics.data.map((topic: { _id: string; title: string }) => (
              <li key={topic._id}>
                <Link href={`/read/${topic._id}`}>{topic.title}</Link>
              </li>
            ))}
          </ol>
        </TopicsProvider>
      </body>
    </html>
  );
}
