import Link from 'next/link'
import './globals.css'
export const metadata = {
  title: 'WEB tutorial',
  description: 'Generated by egoing',
}
export default function Home() {
  return (
    <>
    <h2>Welcome</h2>
    Hello, WEB
    <p><img src="/hello.png" width="80" alt="" /></p>
    </>
  )
}